feat: vbc-36--my-account-removing-reviews
vuestorefront/bigcommerce pull request #100
Opened 2021-12-13 11:02 UTC by scernisevs

Removing My Account - My Reviews page

## Description
Removing My Account - My Reviews page as BigCommerce doesn't link reviews with an account

## Related Issue
VBC-36

## Motivation and Context
Removing My Account - My Reviews page as BigCommerce doesn't link reviews with an account

## How Has This Been Tested?
Locally

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [X] My code follows the code style of this project.
- [X] All new and existing tests passed.

2021-12-13 11:23 UTC, dhargitai requested changes

2021-12-13 11:23 UTC, dhargitai commented on packages/theme/pages/MyAccount.vue
> +import MyReviews from './MyAccount/MyReviews';
Hey @scernisevs, could you remove the other references as well? :)

2021-12-13 12:34 UTC, WojtekTheWebDev approved these changes
LGTM just fix the thing commented by David :)

2021-12-14 09:51 UTC, scernisevs commented on packages/theme/pages/MyAccount.vue
> +import MyReviews from './MyAccount/MyReviews';
great spot, thank you very much @davidhargitai-born

2021-12-14 14:07 UTC, merged