feat(VBC-142): wishlist removeItem action
vuestorefront/bigcommerce pull request #115
Opened 2021-12-21 08:46 UTC by WojtekTheWebDev

useWishlist.removeItem action

## Description

Implementation of useWishlist.removeItem action

## Related Issue

VBC-142

## Motivation and Context

VBC-142

## How Has This Been Tested?

Unit tests

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-12-21 13:41 UTC, zoltantakacs-born requested changes

2021-12-21 13:41 UTC, zoltantakacs-born commented on packages/composables/src/useWishlist/actions/removeItem.ts
> +  { currentWishlist, product: wishlistId }
why wishlistId instead of product or wishlistItem?

2021-12-21 13:41 UTC, zoltantakacs-born commented on packages/composables/__tests__/useWishlist/removeItem.spec.ts
> +    console.log(wishlist);
no console.log

2021-12-21 13:41 UTC, zoltantakacs-born commented on packages/composables/__tests__/useWishlist/removeItem.spec.ts
> +    wishlist = mockedWishlist;
why? both variable will point to the same data

2021-12-21 13:41 UTC, zoltantakacs-born commented on packages/composables/__tests__/useWishlist/removeItem.spec.ts
> +    wishlist.items.push(wishlistItem);
I think the wishlistItem will be twice in the array after the second test (before each test it pushes to the array)

2022-01-03 11:28 UTC, zoltantakacs-born approved these changes

2022-01-03 11:44 UTC, dhargitai approved these changes
👍

2022-01-03 12:28 UTC, merged