Related products: actions for add to cart/wishlist
vuestorefront/bigcommerce pull request #121
Opened 2022-01-04 12:48 UTC by zoltantakacs-born

The action buttons on the related product cards should work as expected.

## Related Issue
VBC-350

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-01-05 10:13 UTC, scernisevs commented on vetur.config.js
> +module.exports = {
hi @zoltantakacs-born ,
Could i please ask you to remove the file from the PR?
vetur it's a great tool but i don't think that everyone is using the extension on this project

2022-01-05 13:20 UTC, dhargitai approved these changes
Looks good

2022-01-05 13:30 UTC, WojtekTheWebDev requested changes
Good job, small remark from me in the comment below

2022-01-05 13:30 UTC, WojtekTheWebDev commented on packages/theme/components/RelatedProducts.vue
> +    onMounted(() => {
After [this PR](https://github.com/vuestorefront/bigcommerce/pull/123) you don't need to load the wishlist in the component, default layout is handling that

2022-01-06 11:11 UTC, scernisevs approved these changes

2022-01-07 09:10 UTC, WojtekTheWebDev approved these changes
LGMT

2022-01-07 09:24 UTC, merged