feat: add link to redirect to homepage
vuestorefront/bigcommerce pull request #134
Opened 2022-01-07 20:25 UTC by darocha

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [x ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

2022-01-10 09:05 UTC, zoltantakacs-born requested changes

2022-01-10 09:05 UTC, zoltantakacs-born commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +          </a>
use nuxt-link instead (with `a` tag the browser will handle the redirect, but in SPAs the app should handle inner navigations)

2022-01-10 10:41 UTC, dhargitai approved these changes
Please just fix what Zoltan mentioned, otherwise looks good so I approve.

2022-01-10 13:44 UTC, darocha commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +          </a>
Hi Zoltan. good catch already replaced. Thanks.

2022-01-11 11:58 UTC, scernisevs approved these changes

2022-01-11 16:05 UTC, zoltantakacs-born approved these changes

2022-01-11 16:16 UTC, merged