feat: getProducts api-client
vuestorefront/bigcommerce pull request #16
Opened 2021-11-05 13:48 UTC by zoltantakacs-born

getProducts function to request products from bigcommerce API.

## Description

## Related Issue
[VBC-21](https://borngroup.atlassian.net/browse/VBC-21)

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-11-08 07:44 UTC, WojtekTheWebDev approved these changes
Only 1 small remark in the comment

2021-11-08 07:44 UTC, WojtekTheWebDev commented on packages/api-client/src/types/api/products.ts
> +type Image = {
Can you extract this part and import it from another file like api-client/src/types/api/product/image.ts ?

2021-11-08 09:54 UTC, scernisevs commented on packages/composables/src/getters/productGetters.ts
> +  return products ?? [];
hi @zoltantakacs-born ,

Could we please add a "TODO" comment in here, to come back to this function together with Configurable Products and product variation development

2021-11-08 13:54 UTC, WojtekTheWebDev approved these changes

2021-11-08 14:33 UTC, dhargitai requested changes

2021-11-08 14:33 UTC, dhargitai commented on packages/api-client/src/api/product/get/index.ts
> +    queryString.stringifyUrl({ url: '/catalog/products', query: params })
Hey Zoli, I've been asked to use a separate file to store the string constants for the API endpoints.
Maybe could you use it as well?

https://github.com/vuestorefront/bigcommerce/pull/17/files#diff-e18d8be656d639eaa5fc9cf089de6976b1300430a06b81bdb2d98345d5e2a03d

2021-11-08 14:33 UTC, dhargitai commented on packages/api-client/src/types/api/endpoints/index.ts
> +   * @param {GetProductsProps} props An object containinig the filters for products.
There's a typo here.

2021-11-15 13:49 UTC, scernisevs approved these changes
LGTM! :) thank you.

2021-11-15 13:50 UTC, WojtekTheWebDev approved these changes
LGTM, in my other PR I also created types for meta and pagination so we would need to solve the conflicts after merging but nice pr ;)

2021-11-15 13:50 UTC, scernisevs requested changes
LGTM! Thank you :) 
Only the 2 outstanding comments raised by @dhargitai are still needed before this can be merged in!

2021-11-16 09:22 UTC, dhargitai approved these changes
Looks good! :)

2021-11-16 10:02 UTC, scernisevs approved these changes

2021-11-16 10:13 UTC, merged