feat: order history
vuestorefront/bigcommerce pull request #165
Opened 2022-01-17 15:29 UTC by zoltantakacs-born

Show order history for logged in user on account page.

## Related Issue
VBC-402

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-01-17 16:54 UTC, scernisevs commented on packages/api-client/src/index.server.ts
> +  clientV2: client({ ...settings.sdkSettings, apiVersion: undefined })
could we please change apiVersion value to 'v2' rather than undefined?

@WojtekTheWebDev , 
I wanted to ask if the current solution fits the best practice of changing a value of one of clients properties? :)

2022-01-17 17:08 UTC, scernisevs reviewed
Thank you very much for the PR! Great job with the feature fulfilment! 

A couple of questions before approving have been left in the comments

2022-01-17 17:08 UTC, scernisevs commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +    const tableHeaders = ['Order ID', 'Payment date', 'Amount', 'Status'];
super minor but could we please add translation here? 
const { $i18n } = context.root;
const tableHeader = [$i18n.t('Order ID'),...]

2022-01-17 17:08 UTC, scernisevs commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +      const products = await this.$vsf.$bigcommerce.api.getOrderProducts({
would it be possible to deal with this in a new composable?

I definitely understand why you're calling it here rather than on the API / useUserOrder level, as we would have to make a call for each order in the response, and this might be heavy on performance.

I wonder if we could create a new composable useUserOrderItems and fetch the order product data once order details page has been visited?

@WojtekTheWebDev  would be also curious to hear your thoughts

2022-01-18 12:29 UTC, WojtekTheWebDev reviewed
Nice PR @zoltantakacs-born, few questions before merging

2022-01-18 12:29 UTC, WojtekTheWebDev commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +      const products = await this.$vsf.$bigcommerce.api.getOrderProducts({
I agree that having a new composable here is a good idea. Maybe something like useOrderProducts. And I think that it should be a part of vuestorefront/bigcommerce package so it should be in the composables package.

2022-01-18 12:29 UTC, WojtekTheWebDev commented on packages/api-client/src/types/order/responses.ts
> +export type OrdersResponse = Order[] | null;
@zoltantakacs-born what is the case when the response is `null`?

2022-01-18 12:37 UTC, scernisevs commented on packages/composables/src/useUserOrder/actions/search.ts
> +    Array.isArray(channelIds) && channelIds.length ? channelIds[0] : null;
I believe we should be using only 1 channel id (for this app itself). 

When registering a user, BC API expects an array of ChannelID's as its possible to register a user across multiple channels, hence we were keeping the values in an array, I believe if required we could refactor it and keep the variable as channelID in the theme config in a single value. I wonder if there could be cases when the end merchant would like to register a user on multiple instances through this app (i.e. if its being used as an additional channel to the main storefront, we could register the user giving the access to both instances)

2022-01-18 12:40 UTC, WojtekTheWebDev commented on packages/composables/src/useUserOrder/actions/search.ts
> +    Array.isArray(channelIds) && channelIds.length ? channelIds[0] : null;
Thanks for the response @scernisevs so that's ok for now. I see the chance of using multiple channels in case of having store in different languages if I'm correct? But it can be like this for the current scope

2022-01-18 13:51 UTC, WojtekTheWebDev requested changes
Blocked by VBC-413

2022-01-18 13:51 UTC, WojtekTheWebDev commented on packages/api-client/src/index.server.ts
> +  clientV2: client({ ...settings.sdkSettings, apiVersion: 'v2' })
Pls wait for the VBC-413 to be finished, it will affect the current code

2022-01-18 14:01 UTC, zoltantakacs-born commented on packages/api-client/src/types/order/responses.ts
> +export type OrdersResponse = Order[] | null;
if no item has found

2022-01-18 15:44 UTC, WojtekTheWebDev reviewed
Unblocked with https://github.com/vuestorefront/bigcommerce/pull/173

2022-01-20 11:54 UTC, WojtekTheWebDev requested changes
There is one more thing I found, I hope that's the last one :)

2022-01-20 11:54 UTC, WojtekTheWebDev commented on packages/theme/pages/MyAccount/OrderHistory.vue
> +    async handleDetailsClick(order: Order) {
Please move this method to `setup`

2022-01-20 13:27 UTC, scernisevs approved these changes
LGTM, thank you very much

2022-01-20 15:14 UTC, merged