feat: add createCustomer endpoint for register user
vuestorefront/bigcommerce pull request #17
Opened 2021-11-05 14:20 UTC by dhargitai

Add createCustomer endpoint for register user.
Add Jest Watch Typeahead plugin and NPM script to run tests in watch mode.

## Related Issue
https://borngroup.atlassian.net/browse/VBC-30

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-05 20:36 UTC, darocha approved these changes
Thanks for adding the Typeahead plugin.

2021-11-08 07:38 UTC, WojtekTheWebDev reviewed
Nice job @dhargitai, it's nice pr. I added 1 comment about global context mock which could reduce the number of code lines in the test files.

I also might have one suggestion about the file structure. In other VSF integrations I saw another approach, test for api are placed in _api-client/\_\_tests\_\_/api_ and then in the folders for specific case so in your case it would be _api-client/\_\_tests\_\_/api/customer/create.spec.ts_ 
With mocks it's similar but in _api-client/\_\_mocks\_\_/api_ directory.

That's the question to other reviewers, how about following this approach?

2021-11-08 07:38 UTC, WojtekTheWebDev commented on packages/api-client/src/api/endpoints/customers/createCustomer/__tests__/index.spec.ts
> +    const context: {
@dhargitai how about global context mock like this in my PR: https://github.com/vuestorefront/bigcommerce/pull/18/files
Then in test:
```typescript
import { contextMock } from 'pathbefore/__mocks__/context.mock.ts'
/* params and expected response implementation */
contextMock.post = jest.fn(() => Promise.resolve(expectedResponse))
const response = await createCustomer(context, parameters);
/* the rest of the code */
```

2021-11-08 07:53 UTC, Mateuszpietrusinski requested changes
Verify and reply.

2021-11-08 07:53 UTC, Mateuszpietrusinski commented on packages/api-client/src/api/endpoints/customers/createCustomer/index.ts
> +  return data[0];
I think here we should provide some props validation. If required props are undefined we should throw an error

2021-11-08 07:53 UTC, Mateuszpietrusinski commented on packages/api-client/src/api/endpoints/customers/createCustomer/__tests__/index.spec.ts
> +    };
I think we don't need to test the response it depends on external code, our function is responsible to handle just the promise.

2021-11-08 07:53 UTC, Mateuszpietrusinski commented on packages/api-client/src/api/endpoints/customers/createCustomer/index.ts
> +  >('/customers', [params]);
What do you think about extracting the string 'customers' into a separated config file where we can store all the api-endpoints from the e-commerce platform?

2021-11-08 07:53 UTC, Mateuszpietrusinski commented on packages/api-client/src/types/api/endpoints/parameters.ts
> +};
Please provide the documentation for that

2021-11-08 07:53 UTC, Mateuszpietrusinski commented on packages/api-client/src/types/api/endpoints/responses.ts
> +};
Same as above -  Documentation maybe that can help you https://github.com/vuestorefront/bigcommerce/blob/feat/sdk-client/packages/open-api-sdk/src/api/customers_v3/models/CustomerPost.ts

2021-11-08 10:10 UTC, dhargitai commented on packages/api-client/src/types/api/endpoints/index.ts
> +   * Creates the new customer
Hey Stan,

I wanted to place an empty line there, however VSCode constantly deleted it.

I disabled the `typescript.format.enable` setting, but it looks like the Prettier extension has a similar feature which I couldn't disable yet: https://prettier.io/docs/en/rationale.html#empty-lines

2021-11-08 10:16 UTC, scernisevs commented on packages/api-client/src/types/api/endpoints/index.ts
> +   * Creates the new customer
hi David,

thank you very much :) in that case could we please remove the '  // eslint-disable lines-around-comment'
and leave it without a new line

2021-11-08 10:26 UTC, dhargitai commented on packages/api-client/src/types/api/endpoints/index.ts
> +   * Creates the new customer
Sure. In this case could we disable the rule in ESLint config, please? Because it complains about it.

2021-11-08 10:58 UTC, dhargitai commented on packages/api-client/src/api/endpoints/customers/createCustomer/__tests__/index.spec.ts
> +    };
I've put it in for somewhat documenting the response format of the BigCommerce endpoint. I think it's useful but I can remove it.

2021-11-08 11:04 UTC, scernisevs commented on packages/api-client/src/types/api/endpoints/index.ts
> +   * Creates the new customer
As discussed in slack: please leave the comment as is, VBC-2 JIRA ticket will cover the eslint configuration and will remove the ignore rule in this file

2021-11-08 12:46 UTC, dhargitai commented on packages/api-client/src/types/api/endpoints/responses.ts
> +};
Thanks @Mateuszpietrusinski ! 👍

2021-11-08 12:51 UTC, dhargitai commented on packages/api-client/src/api/endpoints/customers/createCustomer/index.ts
> +  >('/customers', [params]);
Good idea, thank you! Now I remember that you showed us this on your initial implementation.

2021-11-09 10:13 UTC, WojtekTheWebDev requested changes
Really nice pr, only one more thing, if you could move packages/api-client/src/types/api/parameters.ts to packages/api-client/src/types/api/**customers**/parameters.ts and the same with requests.ts

2021-11-09 10:39 UTC, WojtekTheWebDev approved these changes

2021-11-09 11:40 UTC, scernisevs approved these changes

2021-11-09 11:48 UTC, zoltantakacs-born approved these changes

2021-11-09 16:30 UTC, WojtekTheWebDev commented on packages/api-client/api-extractor.json
> +  "mainEntryPointFilePath": "./lib/src/index.d.ts",
This would be unnecessary after this PR: https://github.com/vuestorefront/bigcommerce/pull/22

2021-11-10 13:30 UTC, dhargitai commented on packages/api-client/api-extractor.json
> +  "mainEntryPointFilePath": "./lib/src/index.d.ts",
I change this back, thanks!

2021-11-10 13:50 UTC, Mateuszpietrusinski approved these changes
LGTM

2021-11-10 13:51 UTC, Mateuszpietrusinski commented on packages/api-client/src/api/endpoints/customers/createCustomer/__tests__/index.spec.ts
> +    };
If you feel that its better to have that in tests i leave it to you

2021-11-10 14:26 UTC, merged