feat: get product review
vuestorefront/bigcommerce pull request #19
Opened 2021-11-08 11:53 UTC by WojtekTheWebDev

API client for get product review

## Description
Implementation get product review api call with docs and unit tests

## How Has This Been Tested?
Unit tests 

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2021-11-15 13:48 UTC, scernisevs requested changes
The PR Looks great! thank you very much for it.
There are 2 very minor comments related to cosmetics only

2021-11-15 13:48 UTC, scernisevs commented on packages/api-client/__mocks__/review.mock.ts
> +    text: 'anim aute',
Same here, i was wondering if we could change the Lorem Ipsum to something little bit more structural.
Lorem Ipsum is great for placeholder text, but i think in tests it might add value to show +- realistically expected data.

2021-11-15 13:48 UTC, scernisevs commented on packages/composables/src/useReview/index.ts
> +export const useReview = useReviewFactory</* Review */Record<string, unknown>, SearchParams, AddParams>(params);
Could we please remove the commented out Review generic type and its import on line 6 ?

2021-11-15 14:24 UTC, WojtekTheWebDev commented on packages/composables/src/useReview/index.ts
> +export const useReview = useReviewFactory</* Review */Record<string, unknown>, SearchParams, AddParams>(params);
Sure, done ;)

2021-11-15 14:25 UTC, darocha approved these changes
I have not found any issues.

2021-11-16 09:18 UTC, scernisevs approved these changes
LGTM! :)

2021-11-16 09:20 UTC, merged