Feat/category api
vuestorefront/bigcommerce pull request #21
Opened 2021-11-09 04:08 UTC by darocha

## Description

Added getCategory in api-client
Added related tests
Added useCategory in composables

Suggestions and feedback are welcome :) 

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [?] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-15 09:09 UTC, WojtekTheWebDev requested changes
Change base branch to **develop**

2021-11-15 13:44 UTC, scernisevs commented
hi @darocha , could you please let us know by adding the team to the reviewers once this is ready to be reviewed?
Please note that currently its pointing at the 'main' branch instead of 'develop' :)

2021-11-17 02:10 UTC, darocha commented
This PR is for tickets VBC-48, VBC-49 and VBC-50.

2021-11-17 09:22 UTC, scernisevs reviewed
hi Marcelo,

ideally we would like to be braking the PR's into smaller chunks moving forward :) as this one currently covers 3 tickets

2021-11-17 09:22 UTC, scernisevs commented on .eslintrc.json
> +        "./packages/theme/pages/*.vue",
hi Marcelo, i don't think we should be adding any files apart of types, to this rule, we disabled camelCase enforcement on object properties instead.

2021-11-17 13:57 UTC, darocha commented on .eslintrc.json
> +        "./packages/theme/pages/*.vue",
No problem. I'll submit a PR per ticket from now on.

2021-11-17 13:59 UTC, darocha commented on .eslintrc.json
> +        "./packages/theme/pages/*.vue",
Ok, I'll remove lines 149, 148, 151.

2021-11-18 10:26 UTC, scernisevs requested changes
PR Looks Great! :) thank you very much Marcelo, only minor comments about the file structure.

2021-11-18 10:26 UTC, scernisevs commented on packages/composables/__tests__/enhancers/useCategory/enhanceCategoryTree.spec.ts
> +/* eslint-disable camelcase */
hi @darocha ,

I was wondering if we need the enhancers folder? it seems that the enhance category tree will be specific to category composable, i think its fine to keep it directly in useCategory.

That was we also can remove the /* eslint-disable camelcase */ on line 1 as it will match the path in lint

2021-11-18 10:26 UTC, scernisevs commented on packages/composables/src/enhancers/category/enhanceCategoriesTree.ts
> +import { CategoryTree } from '../../types/useCategory';
similar for this one, i was wondering if the helper functions can be moved from the packages/composables/src/enhancers/category/*.ts  into packages/themes/src/composables/useCategory/*.ts + the required references updates.

as the composable package will not be available to the developers building the integrations, we want the composable to return the raw data and all the mapping to happen on the theme level, which can be overwritten per project.

2021-11-18 12:55 UTC, dhargitai requested changes

2021-11-18 12:55 UTC, dhargitai commented on packages/api-client/src/api/category/getCategory/index.ts
> +  const { data } = await context.client.get<any>(get(categoryId));
Hey @darocha , could you provide type data for the response type instead of `any`?

2021-11-18 12:55 UTC, dhargitai commented on packages/api-client/src/api/category/getCategoryTree/index.ts
> +): Promise<any> {
Same here for the response type. You could create the new types inside the `src/api/types` folder.

2021-11-18 12:55 UTC, dhargitai commented on packages/api-client/src/config/bigcommerceEndpoints.ts
> +  category: {
I think we already have a place for these constants in the `src/helpers/endpointPaths/index.ts` file. Could you move them into that file?

2021-11-18 12:55 UTC, dhargitai commented on packages/api-client/src/types/endpoints/index.ts
> +export type Endpoints = unknown;
There's already an `Endpoints` interface inside `src/types/api/index.ts`.

I saw that you refactored the `customers` type folder one level higher. I'm fine with that, but in this case could you refactor the existing `Endpoints` interface content into this file and delete the `types/api` folder entirely?

2021-11-18 12:55 UTC, dhargitai commented on packages/composables/__mocks__/useCategory/categoryTreeMockData.json
> +  "data": [
In my opinion it's a bad idea to place the mock data outside of the actual test case, because it makes it harder to read or modify the test.
What do you think about that? I'm open to discuss this.

2021-11-18 13:31 UTC, WojtekTheWebDev requested changes
Hi @darocha really nice job! I added few comments to fit this code into our standards of the development, when they will be done it would be fine for me 😄

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/api-client/src/types/endpoints/index.ts
> +export type Endpoints = unknown;
Why? We have defined endpoints interface in _packages/api-client/src/types/api/index.ts_

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/api-client/src/types/index.ts
> +export * from './api/review';
It's unnecessary because of `export * from './api'; `
```suggestion
```

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/api-client/src/types/shared/index.ts
> +export type Review = TODO;
```suggestion
```

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/api-client/src/types/shared/index.ts
> +export type ReviewItem = TODO;
```suggestion
```

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/composables/__tests__/enhancers/useCategory/enhanceCategoryTree.spec.ts
> +    const categories = await contextMock.$bigcommerce.api.getCategoryTree();
It would be better to import `getCategoryTree` from the path where composable's action is placed and call it to check if this mock has been called 1 time.

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/composables/src/types/useCategory.ts
> +/**
```suggestion

/**
```

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/composables/src/types/useCategory.ts
> +/**
```suggestion

/**
```

2021-11-18 13:31 UTC, WojtekTheWebDev commented on packages/composables/src/useCategory/index.ts
> +  categorySearch: async (context: Context, params: SearchParams) => {
Can you move this logic into separate file _packages/composables/useCategory/actions/search.ts_? We defined our standards a little bit different, you can look at useUser/useReviews/useProducts examples how it's structured :)

2021-11-18 18:43 UTC, darocha commented on packages/api-client/src/api/category/getCategory/index.ts
> +  const { data } = await context.client.get<any>(get(categoryId));
Ok, I added type for the response. Thanks.

2021-11-18 18:43 UTC, darocha commented on packages/api-client/src/api/category/getCategoryTree/index.ts
> +): Promise<any> {
Ok, I added type for the response. Thanks.

2021-11-18 18:51 UTC, darocha commented on packages/api-client/src/config/bigcommerceEndpoints.ts
> +  category: {
Ok. Moved category endpoints from config to src/helpers/endpointPaths/index.ts  and deleted config folder.

2021-11-18 19:36 UTC, darocha commented on packages/composables/__mocks__/useCategory/categoryTreeMockData.json
> +  "data": [
I think its ok to leave on the same file if the mock data is very small and you don't need to reuse it. Otherwise I prefer  to keep in a separated file. If the mock data is big then it will be even harder to read and compare if you need to scroll the code by a lot. If they are on a separated file we can open them side by side (or up/down) in a split screen which will make easier to read. It also eliminate duplication. :)

2021-11-18 19:38 UTC, darocha commented on packages/composables/__mocks__/useCategory/categoryTreeMockData.json
> +  "data": [
On this case I'm using it in more than one place so I think we should to keep it on a separated file.

2021-11-18 19:47 UTC, darocha commented on packages/composables/__tests__/enhancers/useCategory/enhanceCategoryTree.spec.ts
> +/* eslint-disable camelcase */
Hi Stan, I was wondering the same thing. We don't really need it. I moved the files to useCategory and deleted the enhancers folder. Also removed the line /* eslint-disable camelcase */

2021-11-18 19:57 UTC, darocha commented on packages/composables/src/enhancers/category/enhanceCategoriesTree.ts
> +import { CategoryTree } from '../../types/useCategory';
Ok, I think it makes sense. I'll move them to themes.

2021-11-18 20:22 UTC, darocha commented on packages/api-client/src/api/category/getCategory/index.ts
> +  const { data } = await context.client.get<any>(get(categoryId));
Thanks Wojciech , I created types for the response.

2021-11-18 20:22 UTC, darocha commented on packages/api-client/src/api/category/getCategoryTree/index.ts
> +  const { data } = await context.client.get<any>(getTree());
Thanks Wojciech , I created types for the response.

2021-11-18 20:28 UTC, darocha commented on packages/api-client/src/types/endpoints/index.ts
> +export type Endpoints = unknown;
It is from the boilerplate. I removed the ./types/api folder and moved the endpoints to ./types/endpoints as per David suggestions above.

2021-11-18 20:30 UTC, darocha commented on packages/api-client/src/types/index.ts
> +export * from './api/review';
Nice catch! Removed the api folder and moved the 'review' to same level as 'customers' and 'products'.

2021-11-18 20:30 UTC, darocha commented on packages/api-client/src/types/shared/index.ts
> +export type Review = TODO;
Line deleted.

2021-11-18 20:31 UTC, darocha commented on packages/api-client/src/types/shared/index.ts
> +export type ReviewItem = TODO;
Line deleted.

2021-11-18 20:40 UTC, darocha commented on packages/composables/__tests__/enhancers/useCategory/enhanceCategoryTree.spec.ts
> +    const categories = await contextMock.$bigcommerce.api.getCategoryTree();
Can you give an example please? How can I import the method getCategoryTree from the api-client? Thanks.

2021-11-18 20:42 UTC, darocha commented on packages/composables/src/types/useCategory.ts
> +/**
added line.

2021-11-18 20:42 UTC, darocha commented on packages/composables/src/types/useCategory.ts
> +/**
Added new line.

2021-11-18 20:46 UTC, darocha commented on packages/composables/src/useCategory/index.ts
> +  categorySearch: async (context: Context, params: SearchParams) => {
Thanks Wojciech. I think we'll be moving the helpers to the themes layer and have the composable return raw data.
I'll look at the composables you recommended for future developments. Thanks!

2021-11-19 03:32 UTC, darocha commented on packages/api-client/src/types/endpoints/index.ts
> +export type Endpoints = unknown;
Hi David, thanks I refactored as per your suggestion and deleted the api folder. Thanks!

2021-11-19 03:44 UTC, darocha commented on packages/composables/src/useCategory/index.ts
> +  categorySearch: async (context: Context, params: SearchParams) => {
Hi Wojciech Sikora,
I looked at the implementations on useUser/useReviews/useProducts and refactored the useCategory to match the same structure. Please let me know if I missed anything.
Thanks

2021-11-19 13:33 UTC, scernisevs approved these changes

2021-11-19 13:47 UTC, dhargitai requested changes
Hey @darocha, apart from the two small things it looks good for me, noice work!

2021-11-19 13:47 UTC, dhargitai commented on packages/api-client/src/types/category/index.ts
> +
Hey @darocha , just a minor thing :)

Could you delete the unnecessary empty lines and fix the indentations in this file? Somewhere it's 4 space wide, somewhere 2 and some code blocks are also misaligned.

2021-11-19 13:47 UTC, dhargitai commented on packages/theme/composables/useUiHelpers/index.ts
> +  // eslint-disable-next-line
What was the ESLint issue with these lines?
My assumption is if you type the parameters then these disable lines won't be necessary.

2021-11-19 14:12 UTC, darocha commented on packages/api-client/src/types/category/index.ts
> +
ok, deleted the empty lines.

2021-11-19 14:12 UTC, darocha commented on packages/theme/composables/useUiHelpers/index.ts
> +  // eslint-disable-next-line
You are correct.  Removed the commented line // eslint-disable-next-line

2021-11-19 14:32 UTC, dhargitai approved these changes
👍

2021-11-19 15:01 UTC, WojtekTheWebDev requested changes
Nice job, it's almost there. I changes another vsf integration for this `null` type and they have any there so let's follow them. And small request to change the file structure according to the standards :)

2021-11-19 15:08 UTC, darocha commented on packages/composables/src/useCategory/params.ts
> +export const params: UseCategoryFactoryParams<CategoryTree, null> = {
Ok, I changed to any.

2021-11-19 16:39 UTC, WojtekTheWebDev approved these changes
LGTM

2021-11-19 16:46 UTC, merged

2021-11-19 17:39 UTC, darocha commented on packages/api-client/src/types/category/index.ts
> +export type CategoryTree = {
rearrange the folders as per your suggestions. I'll create a new pr.