fix: add type checking to templates
vuestorefront/bigcommerce pull request #230
Opened 2022-02-02 14:52 UTC by zoltantakacs-born

Type checking didn't work for some of the Vue templates.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-02-02 14:56 UTC, scernisevs approved these changes
LGTM

2022-02-02 16:00 UTC, dhargitai approved these changes
Looks good

2022-02-02 16:32 UTC, WojtekTheWebDev requested changes
Nice job, just one suggestion with usage of `ref` and one question

2022-02-02 16:32 UTC, WojtekTheWebDev commented on packages/composables/src/types/useCategory/index.ts
> -import {
We're not using those types?

2022-02-02 16:32 UTC, WojtekTheWebDev commented on packages/theme/components/LoginModal.vue
> +      {} as {
You're using TS here, so you can use ref<{IForgotWhatTypeItWasButForSureItCanBeImprotedFromUserTypes}>();

2022-02-03 08:42 UTC, zoltantakacs-born commented on packages/composables/src/types/useCategory/index.ts
> -import {
No. We use the Category and CategoryTree types coming from the bigcommerce-api package.

2022-02-03 12:16 UTC, WojtekTheWebDev approved these changes
LGTM

2022-02-03 16:45 UTC, WojtekTheWebDev reviewed
LGTM

2022-02-03 16:48 UTC, merged