feat: unit tests for stock data functions
vuestorefront/bigcommerce pull request #275
Opened 2022-02-07 12:39 UTC by zoltantakacs-born

Unit tests for stock data functions.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

2022-02-07 13:10 UTC, WojtekTheWebDev requested changes
It looks good, just few change requests in the comments

2022-02-07 13:10 UTC, WojtekTheWebDev commented on packages/theme/tests/unit/composables/useProductData.spec.ts
> +      productData.canBeAddedToCart({
IMO it would be easier to read and understand the tests if we could define the product outside of `expect` function. Like this:
```js
const expectedProduct = { ... };
expect productData.canBeAddedToCart(expectedProduct).toBe(true);
```

2022-02-07 13:10 UTC, WojtekTheWebDev commented on packages/theme/tests/unit/composables/useProductData.spec.ts
> +      productData.canBeAddedToCart({
The same thing in other test cases in this file

2022-02-07 13:10 UTC, WojtekTheWebDev commented on packages/theme/tests/unit/composables/useWishlistData.spec.ts
> +        wishlistData.isItemPurchasable(
Similar to useProductData, can you define `expectedWishlist` ouside of `expect` function?

2022-02-07 13:22 UTC, dhargitai commented on packages/theme/tests/unit/composables/buildSearchCategories.spec.ts
> +  it('buildSearchCategories should return an array of Category Navigation Items with a correct slug', async () => {
It's just a really simple cosmetic thingy, but if we don't use a test case name that naturally follows the `it` word (like `it('returns an array of ...')`), then maybe we could use `test` instead of `it`.

Like this:
`test('buildSearchCategories should return an array of Category Navigation Items with a correct slug', async () => {`

2022-02-07 13:26 UTC, dhargitai requested changes

2022-02-07 13:26 UTC, dhargitai commented on packages/theme/tests/unit/composables/useProductData.spec.ts
> +    expect(productData.canBeAddedToCart(mockedProduct as Product)).toEqual(
Could you follow the [given] - when - then structure?

So if it needs some preparation (not here), then it could be in the first section of the test, then the actual function call, and after that the expectations on the third section.

This would make these more readable.

2022-02-08 12:59 UTC, scernisevs approved these changes
LGTM thank you very much!

2022-02-09 12:35 UTC, WojtekTheWebDev approved these changes
LGTM

2022-02-09 12:49 UTC, dhargitai approved these changes
Looks good! 👍

2022-02-09 13:06 UTC, merged