feat: api-client for addToCart feature
vuestorefront/bigcommerce pull request #54
Opened 2021-11-24 09:37 UTC by zoltantakacs-born

api-client implementation of adding items to the cart

## Related Issue
VBC-147

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ]

2021-11-24 12:34 UTC, WojtekTheWebDev requested changes
Nice @zoltantakacs-born! I added few comments with missing docs in types, It's a minor but it would be great to add docs to the missing parts :)

2021-11-24 12:34 UTC, WojtekTheWebDev commented on packages/api-client/src/api/cart/addItems/index.ts
> +  return await context.client.post(
Just a small thing, `await` in `return await` is redundant because you're returning the promise anyway
```suggestion
  return context.client.post(
```

2021-11-24 12:34 UTC, WojtekTheWebDev commented on packages/api-client/src/types/cart/contactEntity.ts
> +export type ContactEntity = {
Please add docs
```suggestion
/**
 * Contact entity description
 */
 export type ContactEntity = {
```

2021-11-24 12:34 UTC, WojtekTheWebDev commented on packages/api-client/src/types/cart/customItem.ts
> +  quantity?: string;
Can you provide also `quantity` description?

2021-11-24 12:35 UTC, WojtekTheWebDev commented on packages/api-client/src/types/cart/parameters.ts
> +type GiftCertificateRequest = Omit<GiftCertificate, 'id' | 'isTaxable'> & {
Can you provide some docs description to the types in this file also?

2021-11-24 13:37 UTC, zoltantakacs-born commented on packages/api-client/src/api/cart/addItems/index.ts
> +  return await context.client.post(
they are not the same:
https://stackoverflow.com/questions/38708550/difference-between-return-await-promise-and-return-promise
there is also an eslint rule to require await for every async function to make refactoring more error prune: [require-await](https://eslint.org/docs/rules/require-await)

2021-11-24 13:48 UTC, WojtekTheWebDev commented on packages/api-client/src/api/cart/addItems/index.ts
> +  return await context.client.post(
Hm didn't realise the case with try/catch blocks, in my previous project there was a rule to remove every await from return await ;p But good to know that! Then I'm resolving the conversation

2021-11-25 16:31 UTC, scernisevs approved these changes
LGTM! :) Good to merge after resolving Wojciech comment about missing the types docs

2021-11-29 08:16 UTC, WojtekTheWebDev approved these changes
LGTM

2021-11-29 08:42 UTC, merged