feat(VBC-123): load guest wishlist
vuestorefront/bigcommerce pull request #62
Opened 2021-11-29 14:26 UTC by WojtekTheWebDev

Load action for the guest wishlist

## Description
Implementation of load action for the guest wishlist 

## Related Issue
VBC-123

## Motivation and Context

## How Has This Been Tested?

Unit tests

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-11-30 13:47 UTC, darocha approved these changes
No change requests from me. It's ok to merge.

2021-11-30 14:15 UTC, zoltantakacs-born requested changes

2021-11-30 14:15 UTC, zoltantakacs-born commented on packages/composables/__mocks__/localStorage.mock.ts
> +})();
This is not used.

2021-11-30 14:15 UTC, zoltantakacs-born commented on packages/composables/src/useGuestWishlist/actions/load.ts
> +  const localStorageItem = localStorage.getItem('bigcommerce-wishlist');
Could you please store the name of the localstorage key in a contant and use that in here and unit tests as well?

2021-11-30 14:15 UTC, zoltantakacs-born commented on packages/composables/src/useGuestWishlist/actions/load.ts
> +  guestWishlist = JSON.parse(localStorageItem);
some error handling with try catch would be nice

2021-11-30 16:07 UTC, WojtekTheWebDev commented on packages/composables/src/useGuestWishlist/actions/load.ts
> +  guestWishlist = JSON.parse(localStorageItem);
Error handling is in the `useGuestWishlist`'s `load` method:
<img width="555" alt="Screenshot 2021-11-30 at 16 49 31" src="https://user-images.githubusercontent.com/35867383/144083577-508f3048-d0d6-4540-ab8d-c626f42f1767.png">

2021-12-01 07:25 UTC, zoltantakacs-born approved these changes

2021-12-01 08:01 UTC, merged