Feat/VBC-120_is_in_guest_wishlist_action
vuestorefront/bigcommerce pull request #72
Opened 2021-12-02 13:46 UTC by WojtekTheWebDev

Add isInWishlist action to useGuestWishlist

## Description

Add isInWishlist action to useGuestWishlist

## Related Issue

VBC-120

## Motivation and Context

User should be able to check if the item is in the wishlist

## How Has This Been Tested?

Unit tests

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-12-02 16:36 UTC, scernisevs approved these changes
LGTM

2021-12-03 08:23 UTC, zoltantakacs-born requested changes

2021-12-03 08:23 UTC, zoltantakacs-born commented on packages/composables/src/useGuestWishlist/actions/isInWishlist.ts
> +  }
I think it should not load the wishlist again, just use the already loaded data. You should pass the currentWishlist to this function from the factory. (You can also check the useCartFactory if it is not clear)

2021-12-03 09:14 UTC, WojtekTheWebDev commented on packages/composables/src/useGuestWishlist/actions/isInWishlist.ts
> +  }
ty @zoltantakacs-born, changed.

2021-12-03 13:08 UTC, zoltantakacs-born approved these changes

2021-12-03 13:08 UTC, zoltantakacs-born commented on packages/composables/__tests__/useGuestWishlist/isInWishlist.spec.ts
> +  });
duplicated

2021-12-03 15:00 UTC, merged