Feat: my account - my profile page
vuestorefront/bigcommerce pull request #82
Opened 2021-12-06 23:45 UTC by darocha

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

2021-12-07 10:22 UTC, scernisevs reviewed
hi @darocha ,

Thank you very much for the PR! it looks great :) 

I've left a couple of comments and was wondering if we could please aim to keep the PR at around 500 lines (this one is 1000).  it might be little bit easier to review it if its broken down

2021-12-07 10:22 UTC, scernisevs commented on packages/composables/src/useUser/params.ts
>    load: async (context: Context): Promise<User> => {
hi @darocha ,

I was wondering if we could please brake down the props file for each action to be separate and add unit tests for each action as well? :)

2021-12-07 15:46 UTC, zoltantakacs-born requested changes

2021-12-07 15:46 UTC, zoltantakacs-born commented on packages/composables/src/useUser/params.ts
> +    return null;
the logIn function what is implemented already (`packages/composables/src/useUser/actions/login.ts`) is good, the only modification needed there to get the customer data and return that in that function (and modified the type of the return value)

2021-12-07 18:48 UTC, darocha commented on packages/composables/src/useUser/actions/register.ts
> +import { Context } from '@vue-storefront/core';
No problem, I changed the code to use the custom context.

2021-12-07 18:49 UTC, darocha commented on packages/composables/src/useUser/params.ts
>    load: async (context: Context): Promise<User> => {
Sure, I moved them to a separated file and added tests as well.

2021-12-07 18:50 UTC, darocha commented on packages/composables/src/useUser/params.ts
> +    return null;
Hi Zoltan. it is already implemented. The login function now return a user object.

2021-12-08 09:57 UTC, WojtekTheWebDev requested changes
Hi @darocha good job! There are few pages added to theme, probably from the `_theme` directory. can you add them to `theme/pages` in separate PR as they are in `_theme` to see what's changed here?

2021-12-09 14:14 UTC, zoltantakacs-born requested changes

2021-12-09 14:14 UTC, zoltantakacs-born commented on packages/theme/composables/useUserData/index.ts
> +};
it is not bad, but not really a composable this way 😄

2021-12-09 14:14 UTC, zoltantakacs-born commented on packages/theme/middleware/is-authenticated.js
> +    context.redirect('/');
is both needed? why?

2021-12-09 14:40 UTC, darocha commented on packages/theme/composables/useUserData/index.ts
> +};
you are correct. I modified to follow the same pattern as the other helpers.. Thanks :)

2021-12-09 15:06 UTC, darocha commented on packages/theme/middleware/is-authenticated.js
> +    context.redirect('/');
No, there should only be one. I removed context.app.router.push('/')

2021-12-09 15:18 UTC, darocha commented on packages/api-client/__tests__/api/customers/get.spec.ts
> +    contextMock.client.get.mockImplementationOnce(() => Promise.resolve());
Good catch Zoltan. I removed the lines above.

2021-12-09 15:56 UTC, merged