feat(vbc-121): guest wishlist in theme
vuestorefront/bigcommerce pull request #85
Opened 2021-12-07 17:36 UTC by WojtekTheWebDev

Use guest wishlist in the `theme`

## Description

Usage of useGuestWishlist composable in the `theme` package. Changes in theme requires to change few things that were inconsistent with theme.

## Related Issue

VBC-121

## Motivation and Context

User should be able to addproducts to the wishlist and remove them from it. User should be able to see this changes in the UI.

## How Has This Been Tested?

Unit tests, manual testing

## Screenshots (if appropriate):
<img width="971" alt="Screenshot 2021-12-07 at 18 35 04" src="https://user-images.githubusercontent.com/35867383/145078429-7ca2863a-5871-469a-a547-e0c976bf6fe0.png">
<img width="971" alt="Screenshot 2021-12-07 at 18 35 16" src="https://user-images.githubusercontent.com/35867383/145078453-b87ba590-f9b7-4659-aa8a-4df416397fd8.png">

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-12-07 19:08 UTC, darocha commented on packages/composables/src/useGuestWishlist/helpers/index.ts
> +    'id:in': wishlist.items.length ? wishlist.items.map(item => item.product_id) : [null],
Hi Wojciech, 
Why are we returning an array with a null object when there are no items on the wishlist.items? Did you mean to return an empty array or a null object?

2021-12-07 19:14 UTC, darocha requested changes
Very minor issue. Please look at my previous comment.

2021-12-08 10:01 UTC, WojtekTheWebDev commented on packages/composables/src/useGuestWishlist/helpers/index.ts
> +    'id:in': wishlist.items.length ? wishlist.items.map(item => item.product_id) : [null],
Thanks for the question @darocha, I'll add some docs to it. This `null` is to ensure that when there are no items, response will contain 0 products, but will return `meta` for this scenario. Empty array in this case mean that this filter is not being set.

2021-12-08 13:41 UTC, darocha commented on packages/composables/src/useGuestWishlist/helpers/index.ts
> +    'id:in': wishlist.items.length ? wishlist.items.map(item => item.product_id) : [null],
Thanks Wojciech!

2021-12-08 13:41 UTC, darocha approved these changes

2021-12-09 09:12 UTC, zoltantakacs-born requested changes

2021-12-09 09:12 UTC, zoltantakacs-born commented on packages/theme/composables/useWishlistData/index.ts
> +  const getItem = (wishlist: Wishlist, params: WishlistParams): WishlistItem => {
```suggestion
  const getItem = (wishlist: Wishlist, params: WishlistParams): WishlistItem | undefined => {
```

2021-12-09 09:12 UTC, zoltantakacs-born commented on packages/theme/composables/useWishlistData/index.ts
>          return price;
iterating twice is longer runtime than just once

```
return wishlist?.wishlist_product_data?.data
     .reduce((price, product) => {
        price += product..fixed_cost_shipping_price;
        return price;
     }, 0) || 0;
```

2021-12-09 09:12 UTC, zoltantakacs-born commented on packages/theme/composables/useWishlistData/index.ts
> +    }).reduce((sum, price) => sum + price);
this could be also solved with only reduce

2021-12-09 09:12 UTC, zoltantakacs-born commented on packages/theme/pages/Category.vue
> +              :isOnWishlist="true"
why is it always true?

2021-12-09 09:12 UTC, zoltantakacs-born commented on packages/theme/composables/useProductData/index.ts
> +  const getDefaultVariant = (product: Product): ProductVariant => {
please use this in the `packages/composables/src/useCart/actions/addItem.ts` file and remove the logic from there

2021-12-09 09:12 UTC, zoltantakacs-born commented on packages/theme/components/WishlistSidebar.vue
> +    }
calling this inside a lifecycle hook would be better, without that it is running on every rerender probably:
https://v3.vuejs.org/guide/composition-api-lifecycle-hooks.html

2021-12-09 09:12 UTC, zoltantakacs-born commented on packages/theme/pages/Category.vue
> +    }
use lifecycle hook

2021-12-09 09:40 UTC, WojtekTheWebDev commented on packages/composables/__tests__/useGuestWishlist/addItem.spec.ts
> +    const wishlistMock: Wishlist = JSON.parse(JSON.stringify(guestWishlistMock));
To create shallow copy of that, without shallow copy my tests were failing, items added in another tests preserves in the current one

2021-12-09 09:41 UTC, WojtekTheWebDev commented on packages/composables/src/useGuestWishlist/index.ts
> +    return isInWishlistHelper(wishlist.value, wishlistParams);
It is also being used in `addItem` action

2021-12-09 13:51 UTC, zoltantakacs-born approved these changes

2021-12-09 13:55 UTC, merged