fix: add rating selector and validation
vuestorefront/bigcommerce pull request #87
Opened 2021-12-08 12:53 UTC by WojtekTheWebDev

Add review form was missing the selection of stars.

## Description

SfRating cannot be used as an input (yet) but there is a SfSelect component to pick the rating and SfRating to show it as stars.

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):
<img width="723" alt="Screenshot 2021-12-08 at 13 50 06" src="https://user-images.githubusercontent.com/35867383/145211542-47746227-6057-43ee-988c-da049ea5de76.png">

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

2021-12-08 13:46 UTC, darocha approved these changes
Nicely done!

2021-12-08 14:44 UTC, dhargitai approved these changes
Looks good 👍

2021-12-09 08:27 UTC, zoltantakacs-born requested changes

2021-12-09 08:27 UTC, zoltantakacs-born commented on packages/theme/components/AddReview.vue
> +                :valid="titleBlur || validText(title)"
is it always valid when the input is blurred?

2021-12-09 08:27 UTC, zoltantakacs-born commented on packages/theme/components/AddReview.vue
> +                  :valid="messageBlur || validText(message)"
same as with the title

2021-12-09 08:27 UTC, zoltantakacs-born commented on packages/theme/components/AddReview.vue
> +      if (!(validText(title.value) || validText(message.value))) {
!validText(message.value)

2021-12-09 08:27 UTC, zoltantakacs-born commented on packages/theme/components/AddReview.vue
> +    }
```
&__icon {
...
}
```
---
is important inevitable?

2021-12-09 08:53 UTC, WojtekTheWebDev commented on packages/theme/components/AddReview.vue
> +                :valid="titleBlur || validText(title)"
I used similar logic like SfUI team in their form example 
<img width="1047" alt="Screenshot 2021-12-09 at 09 49 23" src="https://user-images.githubusercontent.com/35867383/145364261-d57b548f-a578-441d-9af1-f4d5ace1d91a.png">
It's just for the ui purposes to not tigger the error when the focus is on the input

2021-12-09 08:53 UTC, WojtekTheWebDev commented on packages/theme/components/AddReview.vue
> +                  :valid="messageBlur || validText(message)"
The same response as in title
https://github.com/vuestorefront/bigcommerce/pull/87#discussion_r765558434

2021-12-09 12:45 UTC, zoltantakacs-born approved these changes

2021-12-09 12:50 UTC, merged