Feat: my account update user api composable theme integration
vuestorefront/bigcommerce pull request #95
Opened 2021-12-10 00:43 UTC by darocha

## Description

## Related Issue

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x ] I have read the **CONTRIBUTING** document.
- [ x] I have added tests to cover my changes.
- [ x] All new and existing tests passed.

2021-12-10 09:20 UTC, WojtekTheWebDev requested changes
Code looks good! I see that build is failing, can you check what's wrong? Then it would be fine for me :)

2021-12-10 09:34 UTC, dhargitai requested changes
Nice work @darocha!
I have 2 minor comments, but otherwise it looks all good.

2021-12-10 09:34 UTC, dhargitai commented on packages/composables/src/useUser/actions/getCustomers.ts
> +export const getCustomers = async (
Hey @darocha 
I don't think we need to rename this to plural as it's returning only one customer.

2021-12-10 09:34 UTC, dhargitai commented on packages/composables/src/useUser/actions/updateCustomers.ts
> +export const updateCustomers = async (
Same here, I think this should be in singular form. (as it's stated in the comment)

2021-12-10 13:31 UTC, darocha commented on packages/composables/src/useUser/actions/getCustomers.ts
> +export const getCustomers = async (
I changed to match the api-client as it returns an array of customers. But I can change back if you prefer.

2021-12-10 13:35 UTC, darocha commented on packages/composables/src/useUser/actions/updateCustomers.ts
> +export const updateCustomers = async (
I can change to singular here also if you like.

2021-12-10 13:36 UTC, dhargitai commented on packages/composables/src/useUser/actions/getCustomers.ts
> +export const getCustomers = async (
You're right, this is the composable, not the api client, I was dumb. Sorry about that, please don't mind me here. :)

2021-12-14 09:40 UTC, scernisevs approved these changes
LGTM :)

2021-12-14 10:52 UTC, dhargitai approved these changes
All looks good :)

2021-12-14 11:08 UTC, zoltantakacs-born commented on packages/api-client/__tests__/api/customers/get.spec.ts
>      );
I know this has been discussed, just my opinions:
- The bigcommerce API is returning an array of customers and we want to support the whole functionality of the API, so we also return the whole array. It can contain one or many customers controlled by the input parameters, but it is plural by default.
- The composable has custom functionality for providing data to the user interface. The getCustomer function is used to get the data for only one customer at a time (the currently authenticated user), so that should be in singular form in my opinion.

2021-12-14 11:20 UTC, scernisevs commented on packages/api-client/__tests__/api/customers/get.spec.ts
>      );
hi @zoltantakacs-born ,

You're absolutely right about that, but i don't think we will ever want to return more than 1 customer for security purposes on the store front.

2021-12-14 11:37 UTC, scernisevs commented on packages/composables/src/useUser/actions/updateCustomer.ts
> +    ...params?.updatedUserData
corrected now :)

2021-12-14 11:44 UTC, zoltantakacs-born commented on packages/api-client/__tests__/api/customers/get.spec.ts
>      );
It is not really about our needs. This will be a public bigcommerce sdk package which could be used by anyone for anything which is supported by the API.

2021-12-14 11:46 UTC, zoltantakacs-born approved these changes

2021-12-14 11:51 UTC, WojtekTheWebDev requested changes
It's almost done, just few remarks.

2021-12-14 11:51 UTC, WojtekTheWebDev commented on packages/composables/src/useUser/actions/load.ts
> +  return null;
I think it might be good to throw an error `if (!loggedInCustomerToken)` which will be handled in try/catch block of `useUser` instead of returning `null`

2021-12-14 11:51 UTC, WojtekTheWebDev commented on packages/api-client/src/types/customers/parameters.ts
> +export type getCustomerParameters = {
```suggestion
export type GetCustomerParameters = {
```

2021-12-14 11:51 UTC, WojtekTheWebDev commented on packages/api-client/src/types/customers/parameters.ts
> +export type updateCustomerParameters = {
```suggestion
export type UpdateCustomerParameters = {
```

2021-12-14 12:54 UTC, WojtekTheWebDev approved these changes
LGTM

2021-12-14 13:03 UTC, merged